name: CybridApiBankSwift
targets:
  CybridApiBankSwift:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [CybridApiBankSwift/APIClient]
    info:
      path: ./Info.plist
      version: 0.121.3
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
