//
// PlansAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PlansAPI {

    /**
     Create Plan
     
     - parameter postPlanBankModel: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func createPlan(postPlanBankModel: PostPlanBankModel, apiResponseQueue: DispatchQueue = CybridApiBankSwiftAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<PlanBankModel, ErrorResponse>) -> Void)) -> RequestTask {
        return createPlanWithRequestBuilder(postPlanBankModel: postPlanBankModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Create Plan
     - POST /api/plans
     - Creates a plan.  ## Create a plan  Plans can be created for a Bank or a Customer.  To create plan for your Bank, omit the `customer_guid` parameter in the request body. To create plans for your Customers, include the `customer_guid` parameter in the request body.  | State | Description | |-------|-------------| | storing | The Platform is storing the plan details in our private store | | planning | The Platform is currently building the plan | | completed | The Platform has successfully completed the plan | | failed | The Platform was not able to successfully complete the plan |    Required scope: **plans:execute**
     - BASIC:
       - type: http
       - name: BearerAuth
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter postPlanBankModel: (body)  
     - returns: RequestBuilder<PlanBankModel> 
     */
    open class func createPlanWithRequestBuilder(postPlanBankModel: PostPlanBankModel) -> RequestBuilder<PlanBankModel> {
        let localVariablePath = "/api/plans"
        let localVariableURLString = CybridApiBankSwiftAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postPlanBankModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlanBankModel>.Type = CybridApiBankSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Get Plan
     
     - parameter planGuid: (path) Identifier for the payment instruction. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func getPlan(planGuid: String, apiResponseQueue: DispatchQueue = CybridApiBankSwiftAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<PlanBankModel, ErrorResponse>) -> Void)) -> RequestTask {
        return getPlanWithRequestBuilder(planGuid: planGuid).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Get Plan
     - GET /api/plans/{plan_guid}
     - Retrieves a plan.  Required scope: **plans:read**
     - BASIC:
       - type: http
       - name: BearerAuth
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter planGuid: (path) Identifier for the payment instruction. 
     - returns: RequestBuilder<PlanBankModel> 
     */
    open class func getPlanWithRequestBuilder(planGuid: String) -> RequestBuilder<PlanBankModel> {
        var localVariablePath = "/api/plans/{plan_guid}"
        let planGuidPreEscape = "\(APIHelper.mapValueToPathItem(planGuid))"
        let planGuidPostEscape = planGuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{plan_guid}", with: planGuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = CybridApiBankSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlanBankModel>.Type = CybridApiBankSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Get plans list
     
     - parameter page: (query) The page index to retrieve. (optional)
     - parameter perPage: (query) The number of entities per page to return. (optional)
     - parameter guid: (query) Comma separated plan_guids to list plans for. (optional)
     - parameter bankGuid: (query) Comma separated bank_guids to list plans for. (optional)
     - parameter customerGuid: (query) Comma separated customer_guids to list plans for. (optional)
     - parameter type: (query) Comma separated types to list plans for. (optional)
     - parameter state: (query) Comma separated states to list plans for. (optional)
     - parameter sourceAccountGuid: (query) Comma separated source account guids to list plans for. (optional)
     - parameter destinationAccountGuid: (query) Comma separated destination account guids to list plans for. (optional)
     - parameter createdAtGte: (query) Created at start date-time inclusive lower bound, ISO8601. (optional)
     - parameter createdAtLt: (query) Created at end date-time exclusive upper bound, ISO8601. (optional)
     - parameter updatedAtGte: (query) Updated at start date-time inclusive lower bound, ISO8601. (optional)
     - parameter updatedAtLt: (query) Updated at end date-time exclusive upper bound, ISO8601. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func listPlans(page: Int? = nil, perPage: Int? = nil, guid: String? = nil, bankGuid: String? = nil, customerGuid: String? = nil, type: String? = nil, state: String? = nil, sourceAccountGuid: String? = nil, destinationAccountGuid: String? = nil, createdAtGte: String? = nil, createdAtLt: String? = nil, updatedAtGte: String? = nil, updatedAtLt: String? = nil, apiResponseQueue: DispatchQueue = CybridApiBankSwiftAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<PlanListBankModel, ErrorResponse>) -> Void)) -> RequestTask {
        return listPlansWithRequestBuilder(page: page, perPage: perPage, guid: guid, bankGuid: bankGuid, customerGuid: customerGuid, type: type, state: state, sourceAccountGuid: sourceAccountGuid, destinationAccountGuid: destinationAccountGuid, createdAtGte: createdAtGte, createdAtLt: createdAtLt, updatedAtGte: updatedAtGte, updatedAtLt: updatedAtLt).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Get plans list
     - GET /api/plans
     - Retrieves a listing of plans. Records are sorted by creation date in descending order.  Required scope: **plans:read**
     - BASIC:
       - type: http
       - name: BearerAuth
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter page: (query) The page index to retrieve. (optional)
     - parameter perPage: (query) The number of entities per page to return. (optional)
     - parameter guid: (query) Comma separated plan_guids to list plans for. (optional)
     - parameter bankGuid: (query) Comma separated bank_guids to list plans for. (optional)
     - parameter customerGuid: (query) Comma separated customer_guids to list plans for. (optional)
     - parameter type: (query) Comma separated types to list plans for. (optional)
     - parameter state: (query) Comma separated states to list plans for. (optional)
     - parameter sourceAccountGuid: (query) Comma separated source account guids to list plans for. (optional)
     - parameter destinationAccountGuid: (query) Comma separated destination account guids to list plans for. (optional)
     - parameter createdAtGte: (query) Created at start date-time inclusive lower bound, ISO8601. (optional)
     - parameter createdAtLt: (query) Created at end date-time exclusive upper bound, ISO8601. (optional)
     - parameter updatedAtGte: (query) Updated at start date-time inclusive lower bound, ISO8601. (optional)
     - parameter updatedAtLt: (query) Updated at end date-time exclusive upper bound, ISO8601. (optional)
     - returns: RequestBuilder<PlanListBankModel> 
     */
    open class func listPlansWithRequestBuilder(page: Int? = nil, perPage: Int? = nil, guid: String? = nil, bankGuid: String? = nil, customerGuid: String? = nil, type: String? = nil, state: String? = nil, sourceAccountGuid: String? = nil, destinationAccountGuid: String? = nil, createdAtGte: String? = nil, createdAtLt: String? = nil, updatedAtGte: String? = nil, updatedAtLt: String? = nil) -> RequestBuilder<PlanListBankModel> {
        let localVariablePath = "/api/plans"
        let localVariableURLString = CybridApiBankSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(),
            "per_page": perPage?.encodeToJSON(),
            "guid": guid?.encodeToJSON(),
            "bank_guid": bankGuid?.encodeToJSON(),
            "customer_guid": customerGuid?.encodeToJSON(),
            "type": type?.encodeToJSON(),
            "state": state?.encodeToJSON(),
            "source_account_guid": sourceAccountGuid?.encodeToJSON(),
            "destination_account_guid": destinationAccountGuid?.encodeToJSON(),
            "created_at_gte": createdAtGte?.encodeToJSON(),
            "created_at_lt": createdAtLt?.encodeToJSON(),
            "updated_at_gte": updatedAtGte?.encodeToJSON(),
            "updated_at_lt": updatedAtLt?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlanListBankModel>.Type = CybridApiBankSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
