//
// SardineSessionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SardineSessionsAPI {

    /**
     Create Sardine Session
     
     - parameter postSardineSessionBankModel: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func createSardineSession(postSardineSessionBankModel: PostSardineSessionBankModel, apiResponseQueue: DispatchQueue = CybridApiBankSwiftAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<SardineSessionBankModel, ErrorResponse>) -> Void)) -> RequestTask {
        return createSardineSessionWithRequestBuilder(postSardineSessionBankModel: postSardineSessionBankModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Create Sardine Session
     - POST /api/sardine_sessions
     - Create a Sardine session.  Required scope: **sardine_sessions:execute**
     - BASIC:
       - type: http
       - name: BearerAuth
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter postSardineSessionBankModel: (body)  
     - returns: RequestBuilder<SardineSessionBankModel> 
     */
    open class func createSardineSessionWithRequestBuilder(postSardineSessionBankModel: PostSardineSessionBankModel) -> RequestBuilder<SardineSessionBankModel> {
        let localVariablePath = "/api/sardine_sessions"
        let localVariableURLString = CybridApiBankSwiftAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postSardineSessionBankModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SardineSessionBankModel>.Type = CybridApiBankSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
