//
// AssetBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssetBankModel: Codable, JSONEncodable, Hashable {

    /** The asset type; one of fiat or crypto. */
    public var type: String
    /** The unique code for the asset. */
    public var code: String
    /** The name of the asset. */
    public var name: String
    /** The currency symbol for the asset. */
    public var symbol: String
    /** The number of decimals for the default unit of the asset. */
    public var decimals: Int

    public init(type: String, code: String, name: String, symbol: String, decimals: Int) {
        self.type = type
        self.code = code
        self.name = name
        self.symbol = symbol
        self.decimals = decimals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case code
        case name
        case symbol
        case decimals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(decimals, forKey: .decimals)
    }
}

