//
// AssetTypesBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AssetTypesBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case fiat = "fiat"
    case crypto = "crypto"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
