//
// BankFeatureBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum BankFeatureBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case kycIdentityVerifications = "kyc_identity_verifications"
    case attestationIdentityRecords = "attestation_identity_records"
    case attestationIdentityRecordsV2 = "attestation_identity_records_v2"
    case rawRoutingDetails = "raw_routing_details"
    case individualCustomers = "individual_customers"
    case businessCustomers = "business_customers"
    case counterpartyExternalAccounts = "counterparty_external_accounts"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
