//
// DepositBankAccountRoutingNumberTypeBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DepositBankAccountRoutingNumberTypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case cpa = "CPA"
    case aba = "ABA"
    case swift = "SWIFT"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
