//
// DepositBankAccountStateBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DepositBankAccountStateBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case storing = "storing"
    case created = "created"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
