//
// EffectiveRateBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The effective rate, in destination units per source unit. */
public struct EffectiveRateBankModel: Codable, JSONEncodable, Hashable {

    /** The asset converted from, e.g., USD. */
    public var sourceAsset: String
    /** The asset converted to, e.g., MXN. */
    public var destinationAsset: String
    /** The quoted effective rate as a decimal string. Null until quoted amounts are known. */
    public var quoted: String?
    /** The executed effective rate as a decimal string. Null until execution completes. */
    public var executed: String?

    public init(sourceAsset: String, destinationAsset: String, quoted: String? = nil, executed: String? = nil) {
        self.sourceAsset = sourceAsset
        self.destinationAsset = destinationAsset
        self.quoted = quoted
        self.executed = executed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sourceAsset = "source_asset"
        case destinationAsset = "destination_asset"
        case quoted
        case executed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sourceAsset, forKey: .sourceAsset)
        try container.encode(destinationAsset, forKey: .destinationAsset)
        try container.encodeIfPresent(quoted, forKey: .quoted)
        try container.encodeIfPresent(executed, forKey: .executed)
    }
}

