//
// ExchangeBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class ExchangeBankModel: NSObject, Codable, JSONEncodable {

    public enum ProviderBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case aquanow = "aquanow"
        case dvChain = "dv_chain"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum EnvironmentBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case sandbox = "sandbox"
        case production = "production"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Auto-generated unique identifier for the exchange. */
    public var guid: String?
    /** The name of the exchange. */
    public var name: String?
    /** The provider for the exchange. */
    public var provider: ProviderBankModel?
    /** The environment that the exchange is operating in. */
    public var environment: EnvironmentBankModel?
    /** ISO8601 datetime the exchange was created at. */
    public var createdAt: Date?

    public init(guid: String? = nil, name: String? = nil, provider: ProviderBankModel? = nil, environment: EnvironmentBankModel? = nil, createdAt: Date? = nil) {
        self.guid = guid
        self.name = name
        self.provider = provider
        self.environment = environment
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case name
        case provider
        case environment
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(guid, forKey: .guid)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

