//
// ExecutionBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ExecutionBankModel: Codable, JSONEncodable, Hashable {

    public enum PurposeOfTransactionBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case computerServices = "computer_services"
        case familySupport = "family_support"
        case education = "education"
        case gift = "gift"
        case charitableDonation = "charitable_donation"
        case medicalTreatment = "medical_treatment"
        case maintenanceExpenses = "maintenance_expenses"
        case travel = "travel"
        case hotelAccommodation = "hotel_accommodation"
        case smallValueRemittance = "small_value_remittance"
        case liberalizedRemittance = "liberalized_remittance"
        case personalTransfer = "personal_transfer"
        case loanPayment = "loan_payment"
        case taxPayment = "tax_payment"
        case constructionExpenses = "construction_expenses"
        case advertisingExpenses = "advertising_expenses"
        case advisoryFees = "advisory_fees"
        case businessInsurance = "business_insurance"
        case insuranceClaims = "insurance_claims"
        case deliveryFees = "delivery_fees"
        case serviceCharges = "service_charges"
        case officeExpenses = "office_expenses"
        case propertyPurchase = "property_purchase"
        case propertyRental = "property_rental"
        case royaltyFees = "royalty_fees"
        case sharesInvestment = "shares_investment"
        case fundInvestment = "fund_investment"
        case billPayment = "bill_payment"
        case transportationFees = "transportation_fees"
        case salaryPayment = "salary_payment"
        case rewardPayment = "reward_payment"
        case influencerPayment = "influencer_payment"
        case otherFees = "other_fees"
        case other = "other"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Auto-generated unique identifier for the quote. */
    public var guid: String
    /** The type of product the plan is for; one of remittance. */
    public var type: String
    /** The unique identifier for the plan. */
    public var planGuid: String
    /** The unique identifier for the bank. */
    public var bankGuid: String?
    /** The unique identifier for the customer. */
    public var customerGuid: String?
    /** ISO8601 datetime the record was created at. */
    public var createdAt: Date
    /** ISO8601 datetime the record was last updated at. */
    public var updatedAt: Date
    /** The state of the execution; one of storing, executing, completed, or failed. */
    public var state: String
    /** The failure code for failed executions. */
    public var failureCode: String?
    public var sourceAccount: AccountAssociationBankModel
    public var destinationAccount: AccountAssociationBankModel
    /** The stages of the execution. */
    public var stages: [StageBankModel]
    /** The fees associated with the execution. */
    public var fees: [FeeAssociationBankModel]
    public var travelRuleInfo: ExecutionTravelRuleInfoBankModel
    /** The purpose of transaction for the execution. */
    public var purposeOfTransaction: PurposeOfTransactionBankModel?

    public init(guid: String, type: String, planGuid: String, bankGuid: String? = nil, customerGuid: String? = nil, createdAt: Date, updatedAt: Date, state: String, failureCode: String? = nil, sourceAccount: AccountAssociationBankModel, destinationAccount: AccountAssociationBankModel, stages: [StageBankModel], fees: [FeeAssociationBankModel], travelRuleInfo: ExecutionTravelRuleInfoBankModel, purposeOfTransaction: PurposeOfTransactionBankModel? = nil) {
        self.guid = guid
        self.type = type
        self.planGuid = planGuid
        self.bankGuid = bankGuid
        self.customerGuid = customerGuid
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.state = state
        self.failureCode = failureCode
        self.sourceAccount = sourceAccount
        self.destinationAccount = destinationAccount
        self.stages = stages
        self.fees = fees
        self.travelRuleInfo = travelRuleInfo
        self.purposeOfTransaction = purposeOfTransaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case type
        case planGuid = "plan_guid"
        case bankGuid = "bank_guid"
        case customerGuid = "customer_guid"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case state
        case failureCode = "failure_code"
        case sourceAccount = "source_account"
        case destinationAccount = "destination_account"
        case stages
        case fees
        case travelRuleInfo = "travel_rule_info"
        case purposeOfTransaction = "purpose_of_transaction"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(guid, forKey: .guid)
        try container.encode(type, forKey: .type)
        try container.encode(planGuid, forKey: .planGuid)
        try container.encodeIfPresent(bankGuid, forKey: .bankGuid)
        try container.encodeIfPresent(customerGuid, forKey: .customerGuid)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(failureCode, forKey: .failureCode)
        try container.encode(sourceAccount, forKey: .sourceAccount)
        try container.encode(destinationAccount, forKey: .destinationAccount)
        try container.encode(stages, forKey: .stages)
        try container.encode(fees, forKey: .fees)
        try container.encode(travelRuleInfo, forKey: .travelRuleInfo)
        try container.encodeIfPresent(purposeOfTransaction, forKey: .purposeOfTransaction)
    }
}

