//
// IdentityVerificationMethodBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IdentityVerificationMethodBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case attested = "attested"
    case documentSubmission = "document_submission"
    case idAndSelfie = "id_and_selfie"
    case taxIdAndSelfie = "tax_id_and_selfie"
    case businessRegistration = "business_registration"
    case plaidIdentityMatch = "plaid_identity_match"
    case attestedOwnership = "attested_ownership"
    case accountOwnership = "account_ownership"
    case watchlists = "watchlists"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
