//
// IdentityVerificationPersonaStateBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IdentityVerificationPersonaStateBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case waiting = "waiting"
    case pending = "pending"
    case reviewing = "reviewing"
    case processing = "processing"
    case expired = "expired"
    case completed = "completed"
    case unknown = "unknown"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
