//
// IdentityVerificationWithDetailsPiiBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The personally identifiable information associated with the identity verification. */
public struct IdentityVerificationWithDetailsPiiBankModel: Codable, JSONEncodable, Hashable {

    public enum BusinessTypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case entity = "entity"
        case soleProprietor = "sole_proprietor"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var name: IdentityVerificationWithDetailsPiiNameBankModel?
    /** The business attested aliases. */
    public var aliases: [IdentityVerificationWithDetailsPiiAliasesInnerBankModel]?
    public var address: IdentityVerificationWithDetailsPiiAddressBankModel?
    /** The attested date of birth. */
    public var dateOfBirth: Date?
    /** The attested phone number. */
    public var phoneNumber: String?
    /** The attested email address. */
    public var emailAddress: String?
    /** The attested occupation. */
    public var occupation: String?
    /** The ISO 3166 country 2-Alpha country code of the customer's citizenship. */
    public var citizenship: String?
    /** The attested website. */
    public var website: String?
    /** The attested nature of business. */
    public var natureOfBusiness: String?
    public var registeredAddress: IdentityVerificationWithDetailsPiiRegisteredAddressBankModel?
    /** The attested business industry. */
    public var businessIndustry: String?
    /** The attested business funds source. */
    public var businessFundsSource: String?
    /** The attested business funds destination. */
    public var businessFundsDestination: String?
    /** The attested business type. */
    public var businessType: BusinessTypeBankModel?
    /** The attested business incorporation date. */
    public var businessIncorporationDate: Date?
    /** The attested identification numbers. */
    public var identificationNumbers: [IdentificationNumberBankModel]?

    public init(name: IdentityVerificationWithDetailsPiiNameBankModel? = nil, aliases: [IdentityVerificationWithDetailsPiiAliasesInnerBankModel]? = nil, address: IdentityVerificationWithDetailsPiiAddressBankModel? = nil, dateOfBirth: Date? = nil, phoneNumber: String? = nil, emailAddress: String? = nil, occupation: String? = nil, citizenship: String? = nil, website: String? = nil, natureOfBusiness: String? = nil, registeredAddress: IdentityVerificationWithDetailsPiiRegisteredAddressBankModel? = nil, businessIndustry: String? = nil, businessFundsSource: String? = nil, businessFundsDestination: String? = nil, businessType: BusinessTypeBankModel? = nil, businessIncorporationDate: Date? = nil, identificationNumbers: [IdentificationNumberBankModel]? = nil) {
        self.name = name
        self.aliases = aliases
        self.address = address
        self.dateOfBirth = dateOfBirth
        self.phoneNumber = phoneNumber
        self.emailAddress = emailAddress
        self.occupation = occupation
        self.citizenship = citizenship
        self.website = website
        self.natureOfBusiness = natureOfBusiness
        self.registeredAddress = registeredAddress
        self.businessIndustry = businessIndustry
        self.businessFundsSource = businessFundsSource
        self.businessFundsDestination = businessFundsDestination
        self.businessType = businessType
        self.businessIncorporationDate = businessIncorporationDate
        self.identificationNumbers = identificationNumbers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case aliases
        case address
        case dateOfBirth = "date_of_birth"
        case phoneNumber = "phone_number"
        case emailAddress = "email_address"
        case occupation
        case citizenship
        case website
        case natureOfBusiness = "nature_of_business"
        case registeredAddress = "registered_address"
        case businessIndustry = "business_industry"
        case businessFundsSource = "business_funds_source"
        case businessFundsDestination = "business_funds_destination"
        case businessType = "business_type"
        case businessIncorporationDate = "business_incorporation_date"
        case identificationNumbers = "identification_numbers"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(aliases, forKey: .aliases)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(dateOfBirth, forKey: .dateOfBirth)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(emailAddress, forKey: .emailAddress)
        try container.encodeIfPresent(occupation, forKey: .occupation)
        try container.encodeIfPresent(citizenship, forKey: .citizenship)
        try container.encodeIfPresent(website, forKey: .website)
        try container.encodeIfPresent(natureOfBusiness, forKey: .natureOfBusiness)
        try container.encodeIfPresent(registeredAddress, forKey: .registeredAddress)
        try container.encodeIfPresent(businessIndustry, forKey: .businessIndustry)
        try container.encodeIfPresent(businessFundsSource, forKey: .businessFundsSource)
        try container.encodeIfPresent(businessFundsDestination, forKey: .businessFundsDestination)
        try container.encodeIfPresent(businessType, forKey: .businessType)
        try container.encodeIfPresent(businessIncorporationDate, forKey: .businessIncorporationDate)
        try container.encodeIfPresent(identificationNumbers, forKey: .identificationNumbers)
    }
}

