//
// InternalPostFeeConfigurationBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InternalPostFeeConfigurationBankModel: Codable, JSONEncodable, Hashable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case platform = "platform"
        case bank = "bank"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum ProductTypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case trading = "trading"
        case savings = "savings"
        case funding = "funding"
        case cryptoTransfer = "crypto_transfer"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum ProductProviderBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case compound = "compound"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The type of configuration. */
    public var type: TypeBankModel
    /** The type of product being configured. */
    public var productType: ProductTypeBankModel
    /** The asset code. */
    public var asset: String
    /** The fees associated with the configuration */
    public var fees: [InternalPostFeeBankModel]
    /** The provider for the product being configured. */
    public var productProvider: ProductProviderBankModel?
    /** The bank identifier that the configuration is associated with. */
    public var bankGuid: String?

    public init(type: TypeBankModel, productType: ProductTypeBankModel, asset: String, fees: [InternalPostFeeBankModel], productProvider: ProductProviderBankModel? = nil, bankGuid: String? = nil) {
        self.type = type
        self.productType = productType
        self.asset = asset
        self.fees = fees
        self.productProvider = productProvider
        self.bankGuid = bankGuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case productType = "product_type"
        case asset
        case fees
        case productProvider = "product_provider"
        case bankGuid = "bank_guid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(productType, forKey: .productType)
        try container.encode(asset, forKey: .asset)
        try container.encode(fees, forKey: .fees)
        try container.encodeIfPresent(productProvider, forKey: .productProvider)
        try container.encodeIfPresent(bankGuid, forKey: .bankGuid)
    }
}

