//
// InternalCreateExchangeSettlementApproval202ResponseBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InternalCreateExchangeSettlementApproval202ResponseBankModel: Codable, JSONEncodable, Hashable {

    /** Auto-generated unique identifier for the exchange settlement. */
    public var guid: String?

    public init(guid: String? = nil) {
        self.guid = guid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(guid, forKey: .guid)
    }
}

