//
// PatchBankBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchBankBankModel: Codable, JSONEncodable, Hashable {

    /** The bank's name. */
    public var name: String?
    /** The bank's list of supported trading symbols. */
    public var supportedTradingSymbols: [String]?
    /** The bank's list of supported fiat assets. */
    public var supportedFiatAccountAssets: [String]?
    /** The bank's list of supported country codes. */
    public var supportedCountryCodes: [String]?

    public init(name: String? = nil, supportedTradingSymbols: [String]? = nil, supportedFiatAccountAssets: [String]? = nil, supportedCountryCodes: [String]? = nil) {
        self.name = name
        self.supportedTradingSymbols = supportedTradingSymbols
        self.supportedFiatAccountAssets = supportedFiatAccountAssets
        self.supportedCountryCodes = supportedCountryCodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case supportedTradingSymbols = "supported_trading_symbols"
        case supportedFiatAccountAssets = "supported_fiat_account_assets"
        case supportedCountryCodes = "supported_country_codes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(supportedTradingSymbols, forKey: .supportedTradingSymbols)
        try container.encodeIfPresent(supportedFiatAccountAssets, forKey: .supportedFiatAccountAssets)
        try container.encodeIfPresent(supportedCountryCodes, forKey: .supportedCountryCodes)
    }
}

