//
// PatchTransferBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for transfer modification. */
public struct PatchTransferBankModel: Codable, JSONEncodable, Hashable {

    /** The source participants for the transfer. */
    public var sourceParticipants: [PatchTransferParticipantBankModel]?
    /** The destination participants for the transfer. */
    public var destinationParticipants: [PatchTransferParticipantBankModel]?

    public init(sourceParticipants: [PatchTransferParticipantBankModel]? = nil, destinationParticipants: [PatchTransferParticipantBankModel]? = nil) {
        self.sourceParticipants = sourceParticipants
        self.destinationParticipants = destinationParticipants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sourceParticipants = "source_participants"
        case destinationParticipants = "destination_participants"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sourceParticipants, forKey: .sourceParticipants)
        try container.encodeIfPresent(destinationParticipants, forKey: .destinationParticipants)
    }
}

