//
// PatchInternalDepositAddressBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchInternalDepositAddressBankModel: Codable, JSONEncodable, Hashable {

    /** ISO8601 datetime the deposit address was stored at. */
    public var storedAt: Date?
    /** The blockchain address. */
    public var address: String?
    /** The blockchain address format. */
    public var format: String?
    /** The blockchain address tag. */
    public var tag: String?

    public init(storedAt: Date? = nil, address: String? = nil, format: String? = nil, tag: String? = nil) {
        self.storedAt = storedAt
        self.address = address
        self.format = format
        self.tag = tag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case storedAt = "stored_at"
        case address
        case format
        case tag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(storedAt, forKey: .storedAt)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(tag, forKey: .tag)
    }
}

