//
// PostIdentityRecordBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class PostIdentityRecordBankModel: NSObject, Codable, JSONEncodable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case attestation = "attestation"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The customer's identifier. */
    public var customerGuid: String
    /** The identity record's type. */
    public var type: TypeBankModel
    public var attestationDetails: PostIdentityRecordAttestationDetailsBankModel

    public init(customerGuid: String, type: TypeBankModel, attestationDetails: PostIdentityRecordAttestationDetailsBankModel) {
        self.customerGuid = customerGuid
        self.type = type
        self.attestationDetails = attestationDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customerGuid = "customer_guid"
        case type
        case attestationDetails = "attestation_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customerGuid, forKey: .customerGuid)
        try container.encode(type, forKey: .type)
        try container.encode(attestationDetails, forKey: .attestationDetails)
    }
}

