//
// PostExternalBankAccountCounterpartyNameBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The account holder&#39;s name. Required when account_kind is raw_routing_details. */
public struct PostExternalBankAccountCounterpartyNameBankModel: Codable, JSONEncodable, Hashable {

    /** The holder's first name; used for individuals. Optional when account_kind is raw_routing_details. */
    public var first: String?
    /** The holder's middle name; used for individuals. Optional when account_kind is raw_routing_details. */
    public var middle: String?
    /** The holder's last name; used for individuals. Optional when account_kind is raw_routing_details. */
    public var last: String?
    /** The holder's full name; used for businesses. Optional when account_kind is raw_routing_details. */
    public var full: String?

    public init(first: String? = nil, middle: String? = nil, last: String? = nil, full: String? = nil) {
        self.first = first
        self.middle = middle
        self.last = last
        self.full = full
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case first
        case middle
        case last
        case full
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(first, forKey: .first)
        try container.encodeIfPresent(middle, forKey: .middle)
        try container.encodeIfPresent(last, forKey: .last)
        try container.encodeIfPresent(full, forKey: .full)
    }
}

