//
// PostInternalCountryCodeConfigurationBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostInternalCountryCodeConfigurationBankModel: Codable, JSONEncodable, Hashable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case platform = "platform"
        case bank = "bank"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum EnvironmentBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case sandbox = "sandbox"
        case production = "production"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The type of savings asset configuration: bank or platform. */
    public var type: TypeBankModel
    /** The environment the configuration is associated with. */
    public var environment: EnvironmentBankModel?
    /** The bank identifier that the configuration is associated with. */
    public var bankGuid: String?
    /** Flag indicating if the symbol is enabled for trading on the platform. */
    public var enabled: Bool
    /** The ISO 3166 2-Alpha country code. */
    public var code: String

    public init(type: TypeBankModel, environment: EnvironmentBankModel?, bankGuid: String? = nil, enabled: Bool, code: String) {
        self.type = type
        self.environment = environment
        self.bankGuid = bankGuid
        self.enabled = enabled
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case environment
        case bankGuid = "bank_guid"
        case enabled
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(environment, forKey: .environment)
        try container.encodeIfPresent(bankGuid, forKey: .bankGuid)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(code, forKey: .code)
    }
}

