//
// PostIdentificationNumberBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostIdentificationNumberBankModel: Codable, JSONEncodable, Hashable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case driversLicense = "drivers_license"
        case passport = "passport"
        case passportCard = "passport_card"
        case residenceCard = "residence_card"
        case socialSecurityNumber = "social_security_number"
        case taxIdentificationNumber = "tax_identification_number"
        case identificationCard = "identification_card"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The source of the identification number. */
    public var type: TypeBankModel
    /** The ISO 3166 country 2-Alpha country code of the identification number issuer. */
    public var issuingCountryCode: String
    /** The identification number. */
    public var identificationNumber: String

    public init(type: TypeBankModel, issuingCountryCode: String, identificationNumber: String) {
        self.type = type
        self.issuingCountryCode = issuingCountryCode
        self.identificationNumber = identificationNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case issuingCountryCode = "issuing_country_code"
        case identificationNumber = "identification_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(issuingCountryCode, forKey: .issuingCountryCode)
        try container.encode(identificationNumber, forKey: .identificationNumber)
    }
}

