//
// PostPlanTravelRuleInfoBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Travel rule information */
public struct PostPlanTravelRuleInfoBankModel: Codable, JSONEncodable, Hashable {

    /** The unique identifier for the ultimate originating party. */
    public var ultimateOriginatingPartyGuid: String?
    /** The unique identifier for the ultimate receiving party. */
    public var ultimateReceivingPartyGuid: String?

    public init(ultimateOriginatingPartyGuid: String? = nil, ultimateReceivingPartyGuid: String? = nil) {
        self.ultimateOriginatingPartyGuid = ultimateOriginatingPartyGuid
        self.ultimateReceivingPartyGuid = ultimateReceivingPartyGuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ultimateOriginatingPartyGuid = "ultimate_originating_party_guid"
        case ultimateReceivingPartyGuid = "ultimate_receiving_party_guid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ultimateOriginatingPartyGuid, forKey: .ultimateOriginatingPartyGuid)
        try container.encodeIfPresent(ultimateReceivingPartyGuid, forKey: .ultimateReceivingPartyGuid)
    }
}

