//
// PostSardineSessionBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for sardine session creation. */
public struct PostSardineSessionBankModel: Codable, JSONEncodable, Hashable {

    /** The GUID of the customer the session is for. Required for organization and bank subject tokens. For customer subject tokens, this is inferred from the token. */
    public var customerGuid: String?

    public init(customerGuid: String? = nil) {
        self.customerGuid = customerGuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customerGuid = "customer_guid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customerGuid, forKey: .customerGuid)
    }
}

