//
// PostInternalCybridAccountBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostInternalCybridAccountBankModel: Codable, JSONEncodable, Hashable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case fee = "fee"
        case gas = "gas"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum EnvironmentBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case sandbox = "sandbox"
        case production = "production"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The account type. */
    public var type: TypeBankModel
    /** The asset code. */
    public var asset: String
    /** The name of the account. */
    public var name: String
    /** The environment. */
    public var environment: EnvironmentBankModel

    public init(type: TypeBankModel, asset: String, name: String, environment: EnvironmentBankModel) {
        self.type = type
        self.asset = asset
        self.name = name
        self.environment = environment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case asset
        case name
        case environment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(asset, forKey: .asset)
        try container.encode(name, forKey: .name)
        try container.encode(environment, forKey: .environment)
    }
}

