//
// PostSupportingDocumentBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Supporting document attached to a plan. */
public struct PostSupportingDocumentBankModel: Codable, JSONEncodable, Hashable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case invoice = "invoice"
        case purchaseOrder = "purchase_order"
        case deliverySlip = "delivery_slip"
        case contract = "contract"
        case billOfLading = "bill_of_lading"
        case others = "others"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The kind of supporting document. */
    public var type: TypeBankModel
    /** File guids backing this document. */
    public var fileGuids: [String]
    /** A reference number identifying this document (e.g. an invoice number). Required for payouts to certain corridors. */
    public var documentReferenceNumber: String?

    public init(type: TypeBankModel, fileGuids: [String], documentReferenceNumber: String? = nil) {
        self.type = type
        self.fileGuids = fileGuids
        self.documentReferenceNumber = documentReferenceNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case fileGuids = "file_guids"
        case documentReferenceNumber = "document_reference_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(fileGuids, forKey: .fileGuids)
        try container.encodeIfPresent(documentReferenceNumber, forKey: .documentReferenceNumber)
    }
}

