//
// PostTradingConfigurationBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostTradingConfigurationBankModel: Codable, JSONEncodable, Hashable {

    /** The asset code. */
    public var asset: String
    /** The fees associated with the configuration */
    public var fees: [PostFeeBankModel]

    public init(asset: String, fees: [PostFeeBankModel]) {
        self.asset = asset
        self.fees = fees
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asset
        case fees
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(asset, forKey: .asset)
        try container.encode(fees, forKey: .fees)
    }
}

