//
// PostExternalWalletBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for external wallet creation. */
public struct PostExternalWalletBankModel: Codable, JSONEncodable, Hashable {

    public enum ExpectedBehavioursBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case forceReview = "force_review"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Name of the external wallet. */
    public var name: String
    /** The customer identifier. */
    public var customerGuid: String?
    /** The counterparty identifier. */
    public var counterpartyGuid: String?
    /** The asset code. */
    public var asset: String
    /** The blockchain wallet address for the wallet. */
    public var address: String
    /** The blockchain tag to use when transferring crypto to the wallet. */
    public var tag: String?
    /** The optional expected behaviour to simulate. Only applicable wallets under sandbox banks. */
    public var expectedBehaviours: [ExpectedBehavioursBankModel]?

    public init(name: String, customerGuid: String? = nil, counterpartyGuid: String? = nil, asset: String, address: String, tag: String? = nil, expectedBehaviours: [ExpectedBehavioursBankModel]? = nil) {
        self.name = name
        self.customerGuid = customerGuid
        self.counterpartyGuid = counterpartyGuid
        self.asset = asset
        self.address = address
        self.tag = tag
        self.expectedBehaviours = expectedBehaviours
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case customerGuid = "customer_guid"
        case counterpartyGuid = "counterparty_guid"
        case asset
        case address
        case tag
        case expectedBehaviours = "expected_behaviours"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(customerGuid, forKey: .customerGuid)
        try container.encodeIfPresent(counterpartyGuid, forKey: .counterpartyGuid)
        try container.encode(asset, forKey: .asset)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(tag, forKey: .tag)
        try container.encodeIfPresent(expectedBehaviours, forKey: .expectedBehaviours)
    }
}

