//
// SardineSessionBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SardineSessionBankModel: Codable, JSONEncodable, Hashable {

    /** Auto-generated unique identifier for the sardine session key. */
    public var guid: String
    /** The session key to initialize the Sardine SDK with. */
    public var sardineSessionKey: String
    /** The unique identifier for the customer. */
    public var customerGuid: String

    public init(guid: String, sardineSessionKey: String, customerGuid: String) {
        self.guid = guid
        self.sardineSessionKey = sardineSessionKey
        self.customerGuid = customerGuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case sardineSessionKey = "sardine_session_key"
        case customerGuid = "customer_guid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(guid, forKey: .guid)
        try container.encode(sardineSessionKey, forKey: .sardineSessionKey)
        try container.encode(customerGuid, forKey: .customerGuid)
    }
}

