//
// StageBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StageBankModel: Codable, JSONEncodable, Hashable {

    /** The unique identifier for the stage. */
    public var guid: String
    /** The type of stage; one of payout, deposit, withdrawal, trade, deposit_return, loss_recovery, or withdrawal_return. */
    public var type: String
    /** The state of the stage; one of storing, planning, planned, executing, completed, or failed. */
    public var state: String
    /** The failure code for failed stages. */
    public var failureCode: String?
    /** Provider-issued identifiers associated with this stage. Always present, possibly empty. */
    public var identifiers: [StageIdentifierBankModel]
    /** Provider-issued links associated with this stage. Always present, possibly empty. */
    public var links: [StageLinkBankModel]
    /** The ISO8601 datetime the stage was created at. */
    public var createdAt: Date
    /** The ISO8601 datetime the stage was last updated at. */
    public var updatedAt: Date
    public var sourceAccount: AccountAssociationBankModel
    public var destinationAccount: AccountAssociationBankModel
    /** The fees associated with the stage. */
    public var fees: [FeeAssociationBankModel]
    public var depositReturnDetails: ReturnDetailsBankModel?
    public var withdrawalReturnDetails: ReturnDetailsBankModel?

    public init(guid: String, type: String, state: String, failureCode: String? = nil, identifiers: [StageIdentifierBankModel], links: [StageLinkBankModel], createdAt: Date, updatedAt: Date, sourceAccount: AccountAssociationBankModel, destinationAccount: AccountAssociationBankModel, fees: [FeeAssociationBankModel], depositReturnDetails: ReturnDetailsBankModel? = nil, withdrawalReturnDetails: ReturnDetailsBankModel? = nil) {
        self.guid = guid
        self.type = type
        self.state = state
        self.failureCode = failureCode
        self.identifiers = identifiers
        self.links = links
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.sourceAccount = sourceAccount
        self.destinationAccount = destinationAccount
        self.fees = fees
        self.depositReturnDetails = depositReturnDetails
        self.withdrawalReturnDetails = withdrawalReturnDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case type
        case state
        case failureCode = "failure_code"
        case identifiers
        case links
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case sourceAccount = "source_account"
        case destinationAccount = "destination_account"
        case fees
        case depositReturnDetails = "deposit_return_details"
        case withdrawalReturnDetails = "withdrawal_return_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(guid, forKey: .guid)
        try container.encode(type, forKey: .type)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(failureCode, forKey: .failureCode)
        try container.encode(identifiers, forKey: .identifiers)
        try container.encode(links, forKey: .links)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(sourceAccount, forKey: .sourceAccount)
        try container.encode(destinationAccount, forKey: .destinationAccount)
        try container.encode(fees, forKey: .fees)
        try container.encodeIfPresent(depositReturnDetails, forKey: .depositReturnDetails)
        try container.encodeIfPresent(withdrawalReturnDetails, forKey: .withdrawalReturnDetails)
    }
}

