//
// TradeStateBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TradeStateBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case storing = "storing"
    case pending = "pending"
    case cancelled = "cancelled"
    case completed = "completed"
    case settling = "settling"
    case failed = "failed"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
