//
// TradeSideBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TradeSideBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case buy = "buy"
    case sell = "sell"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
