//
// TradeBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(BigInt)
import BigInt
#endif

public struct TradeBankModel: Codable, JSONEncodable, Hashable {

    public enum SideBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case buy = "buy"
        case sell = "sell"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum StateBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case storing = "storing"
        case initiating = "initiating"
        case pending = "pending"
        case settling = "settling"
        case completed = "completed"
        case failed = "failed"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Auto-generated unique identifier for the trade. */
    public var guid: String?
    /** The associated customer's identifier. */
    public var customerGuid: String?
    /** The associated quote's identifier. */
    public var quoteGuid: String?
    /** The trade symbol the pricing is related to. Format is asset-counter_asset, e.g., BTC-USD. */
    public var symbol: String?
    /** The direction of the quote: either 'buy' or 'sell'. */
    public var side: SideBankModel?
    /** The trade's state */
    public var state: StateBankModel?
    /** The amount to be received in base units of the currency: currency is \"asset\" for buy and \"counter_asset\" for sell. */
    public var receiveAmount: BigInt?
    /** The amount to be delivered in base units of the currency: currency is \"counter_asset\" for buy and \"asset\" for sell. */
    public var deliverAmount: BigInt?
    /** The fee associated with the trade. Denominated in \"counter_asset\" base units */
    public var fee: BigInt?
    /** ISO8601 datetime the bank was created at. */
    public var createdAt: Date?

    public init(guid: String? = nil, customerGuid: String? = nil, quoteGuid: String? = nil, symbol: String? = nil, side: SideBankModel? = nil, state: StateBankModel? = nil, receiveAmount: BigInt? = nil, deliverAmount: BigInt? = nil, fee: BigInt? = nil, createdAt: Date? = nil) {
        self.guid = guid
        self.customerGuid = customerGuid
        self.quoteGuid = quoteGuid
        self.symbol = symbol
        self.side = side
        self.state = state
        self.receiveAmount = receiveAmount
        self.deliverAmount = deliverAmount
        self.fee = fee
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case customerGuid = "customer_guid"
        case quoteGuid = "quote_guid"
        case symbol
        case side
        case state
        case receiveAmount = "receive_amount"
        case deliverAmount = "deliver_amount"
        case fee
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(guid, forKey: .guid)
        try container.encodeIfPresent(customerGuid, forKey: .customerGuid)
        try container.encodeIfPresent(quoteGuid, forKey: .quoteGuid)
        try container.encodeIfPresent(symbol, forKey: .symbol)
        try container.encodeIfPresent(side, forKey: .side)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(receiveAmount, forKey: .receiveAmount)
        try container.encodeIfPresent(deliverAmount, forKey: .deliverAmount)
        try container.encodeIfPresent(fee, forKey: .fee)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

