//
// TransferSideBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TransferSideBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case deposit = "deposit"
    case withdrawal = "withdrawal"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
