//
// TransferHoldDetailsBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The hold details if a transfer is or will be placed on a hold. */
public struct TransferHoldDetailsBankModel: Codable, JSONEncodable, Hashable {

    /** The list of hold types that are applicable for the transfer; one of administrative or non_administrative. */
    public var applicableTypes: [String]?
    /** The approximate time (in seconds) that the transfer will be held for. */
    public var duration: Int?
    /** ISO8601 datetime the transfer hold was started at. */
    public var startedAt: Date?

    public init(applicableTypes: [String]? = nil, duration: Int? = nil, startedAt: Date? = nil) {
        self.applicableTypes = applicableTypes
        self.duration = duration
        self.startedAt = startedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applicableTypes = "applicable_types"
        case duration
        case startedAt = "started_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(applicableTypes, forKey: .applicableTypes)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
    }
}

