//
// TransferIdentifiersInnerBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransferIdentifiersInnerBankModel: Codable, JSONEncodable, Hashable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case txnHash = "txn_hash"
        case imad = "imad"
        case omad = "omad"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Type of identifier (txn_hash, imad, omad) */
    public var type: TypeBankModel?
    /** The identifier value */
    public var value: String?

    public init(type: TypeBankModel? = nil, value: String? = nil) {
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

