//
// VerificationKeyListBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerificationKeyListBankModel: Codable, JSONEncodable, Hashable {

    /** The total number of records available. */
    public var total: String
    /** The page index to retrieve. */
    public var page: String
    /** The number of entities per page to return. */
    public var perPage: String
    /** Array of VerificationKey entities */
    public var objects: [VerificationKeyBankModel]

    public init(total: String, page: String, perPage: String, objects: [VerificationKeyBankModel]) {
        self.total = total
        self.page = page
        self.perPage = perPage
        self.objects = objects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case page
        case perPage = "per_page"
        case objects
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(page, forKey: .page)
        try container.encode(perPage, forKey: .perPage)
        try container.encode(objects, forKey: .objects)
    }
}

