//
// WorkflowWithDetailsBankModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkflowWithDetailsBankModel: Codable, JSONEncodable, Hashable {

    public enum TypeBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case plaid = "plaid"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum StateBankModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case storing = "storing"
        case completed = "completed"
        case failed = "failed"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Auto-generated unique identifier for the workflow. */
    public var guid: String?
    /** The associated customer's identifier. */
    public var customerGuid: String?
    /** The type of workflow. */
    public var type: TypeBankModel?
    /** The state of the workflow. */
    public var state: StateBankModel?
    /** The failure code for failed workflows. */
    public var failureCode: String?
    /** ISO8601 datetime the record was created at. */
    public var createdAt: Date?
    /** ISO8601 datetime the record was last updated at. */
    public var updatedAt: Date?
    /** The Plaid link token generated by the workflow. */
    public var plaidLinkToken: String?

    public init(guid: String? = nil, customerGuid: String? = nil, type: TypeBankModel? = nil, state: StateBankModel? = nil, failureCode: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, plaidLinkToken: String? = nil) {
        self.guid = guid
        self.customerGuid = customerGuid
        self.type = type
        self.state = state
        self.failureCode = failureCode
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.plaidLinkToken = plaidLinkToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case customerGuid = "customer_guid"
        case type
        case state
        case failureCode = "failure_code"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case plaidLinkToken = "plaid_link_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(guid, forKey: .guid)
        try container.encodeIfPresent(customerGuid, forKey: .customerGuid)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(failureCode, forKey: .failureCode)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(plaidLinkToken, forKey: .plaidLinkToken)
    }
}

